#!/bin/sh

start()
{
	lmod /sys/modules/sync
}

stop()
{
	dmod sync
}

up() 
{
	start
}

down()
{
	stop
}

status()
{
	lsmod | grep "sync" >/dev/null
	return $?
}

if [ -z $1 ]; then
	echo "usage: $0 [start|stop|status|up|down]"
	return 1
fi

$1
